# Generated by Django 2.0.3 on 2018-08-13 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_coderepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='CodeRepository',
        ),
        migrations.AddField(
            model_name='job',
            name='Repository',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
