# Generated by Django 2.0.3 on 2018-08-14 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180814_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Repository',
            new_name='repository',
        ),
    ]
