# Generated by Django 2.0.3 on 2018-08-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180803_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(null=True, verbose_name='Died'),
        ),
    ]
